# Generated by Django 5.0.3 on 2024-05-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
