# Generated by Django 5.0.3 on 2024-06-24 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todoitem_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='myapp.todoitem')),
            ],
        ),
    ]
