# Generated by Django 5.0.3 on 2024-06-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_weightlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='weight',
            new_name='reps',
        ),
    ]
